sudo: required
services:
    - docker

before_install:
    - docker build -t sandeepbatra/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sandeepbatra/docker-react npm run test

